config/routes.rb
Jikken::Application.routes.draw do
  resources :apples

end

app/models/apple.rb
class Apple < ActiveRecord::Base
  attr_accessible :name, :price
end

app/controllers/apples_controller.rb
class ApplesController < ApplicationController
  # GET /apples
  # GET /apples.json
  def index
    @apples = Apple.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @apples }
    end
  end

  # GET /apples/1
  # GET /apples/1.json
  def show
    @apple = Apple.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @apple }
    end
  end

  # GET /apples/new
  # GET /apples/new.json
  def new
    @apple = Apple.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @apple }
    end
  end

  # GET /apples/1/edit
  def edit
    @apple = Apple.find(params[:id])
  end

  # POST /apples
  # POST /apples.json
  def create
    @apple = Apple.new(params[:apple])

    respond_to do |format|
      if @apple.save
        format.html { redirect_to @apple, notice: 'Apple was successfully created.' }
        format.json { render json: @apple, status: :created, location: @apple }
      else
        format.html { render action: "new" }
        format.json { render json: @apple.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /apples/1
  # PUT /apples/1.json
  def update
    @apple = Apple.find(params[:id])

    respond_to do |format|
      if @apple.update_attributes(params[:apple])
        format.html { redirect_to @apple, notice: 'Apple was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @apple.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apples/1
  # DELETE /apples/1.json
  def destroy
    @apple = Apple.find(params[:id])
    @apple.destroy

    respond_to do |format|
      format.html { redirect_to apples_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/apples_helper.rb
module ApplesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apples/_form.html.erb
<%= form_for(@apple) do |f| %>
  <% if @apple.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apple.errors.count, "error") %> prohibited this apple from being saved:</h2>

      <ul>
      <% @apple.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apples/edit.html.erb
<h1>Editing apple</h1>

<%= render 'form' %>

<%= link_to 'Show', @apple %> |
<%= link_to 'Back', apples_path %>

app/views/apples/index.html.erb
<h1>Listing apples</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apples.each do |apple| %>
  <tr>
    <td><%= apple.name %></td>
    <td><%= apple.price %></td>
    <td><%= link_to 'Show', apple %></td>
    <td><%= link_to 'Edit', edit_apple_path(apple) %></td>
    <td><%= link_to 'Destroy', apple, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Apple', new_apple_path %>

app/views/apples/new.html.erb
<h1>New apple</h1>

<%= render 'form' %>

<%= link_to 'Back', apples_path %>

app/views/apples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @apple.name %>
</p>

<p>
  <b>Price:</b>
  <%= @apple.price %>
</p>


<%= link_to 'Edit', edit_apple_path(@apple) %> |
<%= link_to 'Back', apples_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jikken</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>